spring:
  cloud:
    gateway:
      discovery:
        locator:
          # 开启从注册中心动态创建路由的功能
          enabled: true
          # 使用小写服务名，默认是大写
          lower-case-service-id: true
      routes:
        - id: mall-user-service
          uri: lb://mall-user-service
          predicates:
            - Path=/api/user/**
logging:
  level:
    org.springframework.cloud.gateway: debug